### ISSUE TITLE
🐛 parcel build hangs using `parcel-plugin-typescript`

### ISSUE THREAD

**Issue by ccorcos** [fathyb/parcel-plugin-typescript#1]
### 🤔 Expected Behavior
`parcel build` shouldn't hang.

### 😯 Current Behavior
`parcel build` hangs

### 🔦 Context
If I uninstall `parcel-plugin-typescript`, then everything builds without hanging.

Versions:

```
    "parcel-bundler": "^1.2.0",
    "parcel-plugin-typescript": "^0.2.0-astmap.0",
    "typescript": "^2.6.2",
```

Moved from here: https://github.com/parcel-bundler/parcel/issues/237

**Comment by fathyb** [comment]
I just published `parcel-plugin-typescript@0.2.0-next.fix-hang`, can you try it?

**Comment by ccorcos** [comment]
Tried it. Still doesn't work. 

You can test it using this repo:

https://github.com/ccorcos/draw-svg

`npm install`, `npm start`, and `npm build` should be the only commands you need.

`npm build` does exit if the build is cached, so make sure you change the index.tsx file between builds.

**Comment by fathyb** [comment]
I cloned it and ran :
- `npm install`
- `npm run-script build` -> the build didn't hang, the plugin was loaded
- `npm run-script build` -> the build didn't hang, the plugin was not loaded
- `echo '// some cache triggering line' >> index.tsx` to clean the file cache
- `npm run-script build` -> the build didn't hang, the plugin was loaded

Can you run `npm ls parcel-plugin-typescript` and confirm me the version is `0.2.0-next.fix-hang`?

**Comment by ccorcos** [comment]
Oh shit, you're right. I just tried it again and it worked!
